# Generated by Django 4.0.6 on 2022-08-04 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='Author',
            field=models.CharField(default=True, max_length=200),
        ),
        migrations.AddField(
            model_name='book',
            name='DESCRIPTION',
            field=models.CharField(default=True, max_length=200),
        ),
        migrations.AddField(
            model_name='book',
            name='GENRE',
            field=models.CharField(default=True, max_length=200),
        ),
    ]
