# Generated by Django 4.0.6 on 2022-08-04 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_book_author_book_description_book_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Author',
            field=models.CharField(default="Enter Author's name", max_length=200),
        ),
        migrations.AlterField(
            model_name='book',
            name='DESCRIPTION',
            field=models.CharField(default='Enter Description', max_length=200),
        ),
        migrations.AlterField(
            model_name='book',
            name='GENRE',
            field=models.CharField(default='Enter Genre', max_length=200),
        ),
    ]
