# Generated by Django 4.0.5 on 2022-08-25 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_remove_book_author_remove_book_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='Author',
            field=models.CharField(default="Enter Author's name", max_length=200),
        ),
        migrations.AddField(
            model_name='book',
            name='DESCRIPTION',
            field=models.CharField(default='Enter Description', max_length=200),
        ),
        migrations.AddField(
            model_name='book',
            name='GENRE',
            field=models.CharField(default='Enter Genre', max_length=200),
        ),
    ]
