# Generated by Django 4.0.5 on 2022-08-25 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_book_author_book_description_book_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='Publisher',
            field=models.CharField(default='Enter Publisher', max_length=200),
        ),
    ]
